### ISSUE TITLE
[Upstream] Unicode latest emoji support

### ISSUE THREAD

**Issue by omkarnathsingh** [Sea-n/tdesktop#2]
I can't see latest emojis posted on desktop client. I have reported to Tdesktop also, but no update :(

**Comment by Sea-n** [comment]
I hope upstream implement it soon since I can't do as good as the official version.

Here is some reference I found so far.

+ Previous commit 8f8100a
+ Unicode [Emoji versions](https://www.unicode.org/emoji/charts/emoji-versions.html)
+ TDesktop [emoji auto complete.json](https://github.com/Sea-n/tdesktop/blob/dev/Telegram/Resources/emoji_autocomplete.json)

**Comment by Sea-n** [comment]
Sorry for the wrong reference.

I noticed it's [Emoji One](https://github.com/emojione/emojione) project, and didn't update yet.
